image: code.usgs.gov:5001/water/egret:latest

default:
  tags:
    - chs-shared
    - dind

stages:
  - build
  - check
  - test
  - end
  - deploy

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_SUGGESTS_ONLY: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  _R_CHECK_DONTTEST_EXAMPLES_: "false"
  R_PROFILE: "$R_HOME/etc/Rprofile.site"
  APT_CACHE: "$CI_PROJECT_DIR/ci/lib/apt-cache"
  CRAN: "https://rpkg.chs.usgs.gov/prod-cran/latest"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  R_LIBS: "$CI_PROJECT_DIR/ci/lib"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs"
  NOT_CRAN: "true"
  CONNECT_API_KEY: $CONNECT_API_KEY
  CONNECT_SERVER: $CONNECT_SERVER
  PAGES_OUTDIR: "$CI_PROJECT_DIR/public"


buildcheck:
  stage: check
  cache: []
  script:
    - mkdir -p $BUILD_LOGS_DIR
    - R CMD build . --no-manual
    - R -e 'install.packages("EGRET")'
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", check_dir = Sys.getenv("BUILD_LOGS_DIR"), vignettes = FALSE)'

unittests:
  stage: test
  cache: []
  dependencies:
    - buildcheck
  script:
    - R -e 'library(testthat); options(testthat.output_file = file.path(Sys.getenv("CI_PROJECT_DIR"), "test-out.xml")); devtools::test(reporter = "junit")'
  artifacts:
    when: always
    paths: 
      - test-out.xml
    reports:
      junit: test-out.xml

covertests:
  stage: test
  cache: []
  dependencies:
    - buildcheck
  script:
    - R -e 'x <- covr::package_coverage(); covr::to_cobertura(x); x; '
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura.xml
  coverage: '/Coverage: \d+.\d+\%/'

pages:
  stage: end
  cache: []
  only: 
    - main
  script:
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"))'
  artifacts:
    paths:
      - $PAGES_OUTDIR
    expire_in: 1 week
    
Validate Inventory:
    stage: end
    image: ${INTERNAL_REGISTRY}software/software-management:latest
    script:
      - software-management review
        --project "${CI_PROJECT_PATH}"
        --ref "${CI_COMMIT_BRANCH}"
        --type "provisional"
        --token "${GIT_TOKEN_CUSTOM}"
    tags:
        - chs-shared
